name: kartomat
description: Portfel kart lojalnosciowych.
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  screen_brightness: ^1.0.1
  barcode_widget: ^2.0.4
flutter:
  uses-material-design: true
