name: Zbuduj Kartomat APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Generowanie struktury projektu
        run: |
          # Wymuszamy stworzenie brakujących plików Androida
          flutter create --project-name=kartomat . --overwrite
          # Podbijamy minSDK (wymagane przez bibliotekę jasności)
          sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 21/g' android/app/build.gradle
          
      - name: Build
        run: |
          flutter pub get
          flutter build apk --release --split-per-abi
          
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Kartomat-Gotowy
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
